### PR TITLE
Weston 8 compatible

### PR DESCRIPTION
**Pull request by khangtb1**
make the extension compatible with weston 8:
- update libweston in CMakeLists.txt
- fix crash in controller_screenshot_notify

### CODE REVIEW

**Comment by HarshaMM** [comment]
@khangtb1 , 

Along with fix of crash,  it would be nice to include the following patches as well from https://github.com/COVESA/wayland-ivi-extension/pull/119:

https://github.com/COVESA/wayland-ivi-extension/pull/119/commits/94be9f71f5f70eebd727afcb165c338f48e41edf
https://github.com/COVESA/wayland-ivi-extension/pull/119/commits/808fcbe082b94d45f2046087e0b0be9fa7802f4c
https://github.com/COVESA/wayland-ivi-extension/pull/119/commits/acc9251a065638a7ff8ec87c7a5d3606f8c827f3
https://github.com/COVESA/wayland-ivi-extension/pull/119/commits/c34806efbe6bb27a2e0730a83325f4f20939e5de

Also, patches which are adaptations for weston-7 are needed. I am assuming, after weston-7 update relevant PR's are merged, this PR can be taken-in.

**Comment by HarshaMM** [comment]
@khangtb1 ,

https://github.com/COVESA/wayland-ivi-extension/pull/125 is also needed for weston-8 compatibility. It would be great if you can include this one as well.

**Comment by khangtb1** [comment]
@HarshaMM  I just updated this PR follow your suggestion. we are going to test for this + #125.

**Comment by audoan99** [comment]
This pull request works great.
Tested-by: Au Doan Ngoc <au.doanngoc@vn.bosch.com>

**Review by HarshaMM — APPROVED** [review]
Reviewed-by: Harsha M M <harsha.manjulamallikarjun@in.bosch.com>

**Review by efriedrich — APPROVED** [review]
Reviewed-by: Eugen Friedrich <efriedrich@de.adit-jv.com>

**Pull request merged**
