### PR TITLE
Fix header variable defined by pkg_check_module

### PR DESCRIPTION
**Pull request by khangtb1**
Follow the [pkg_check_modules](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html), this function will set a variety of result variables. One of them is header variable, it's formatting is XXXXX_INCLUDE_DIRS, is not XXXXX_INCLUDE_DIR.

### CODE REVIEW

**Comment by audoan99** [comment]
I tested the pull request with list test cases. All has passed.

**Comment by HarshaMM** [comment]
@khangtb1 ,

It would be nice to have single commit containing all changes. The change is very generic across all modules. I do not see a need in future to cherry-pick an individual patch among these.

**Comment by khangtb1** [comment]
@HarshaMM, Thank you for your suggestion, I just reduce the number of commit to 2. There are two issue in this PR:
- First is the pkg_check_modules header variable. I think you clear about it.
- Second is the including of weston header file should not contain the weston directory in the path. The WESTON_INCLUDE_DIRS contains a link to ${install_dir}/include/weston/. If user only build weston before build ivi-extension, the path includes the weston directory will not make sense.

**Comment by HarshaMM** [comment]
@khangtb1 ,

Thank you. I missed that. Now, I see there are three issues:

1. CMake header include variable is incorrect.
2. Use of "weston" dir path in the header inclusion even though WESTON_INCLUDE_DIRS already defines this.
3. Missing linker directory include for libweston-desktop.

Can we have three patches then, for the three issues?

**Comment by khangtb1** [comment]
@HarshaMM I have a fix, following your comment. this's more clear now.

**Comment by HarshaMM** [comment]
@khangtb1 ,

Thank you. 

@efriedrich ,

Can you please take a look?

**Review by HarshaMM — APPROVED** [review]

**Review by efriedrich — APPROVED** [review]
Reviewed-by: Eugen Friedrich <efriedrich@de.adit-jv.com>

**Pull request merged**
