### PR TITLE
CMake: Specify generic library destination for installation

### PR DESCRIPTION
**Pull request by rajendraprasadkj**
The libraries generated are now installed in lib${LIB_SUFFIX} (lib/lib32/lib64) directory. This doesn't work with Debian as it expects libraries to be present in lib/multiarch-tuple.

Set the library destination path to 'CMAKE_INSTALL_LIBDIR'.

### CODE REVIEW

**Comment by HarshaMM** [comment]
@rajendraprasadkj ,

I also see necessity include the module https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html. I do not have an extensive knowledge of cmake. It would be great if you can check need for inclusion of gnuinstalldir

**Comment by khangtb1** [comment]
Hi @rajendraprasadkj 

As I understand this PR here: when using the CMAKE_INSTALL_LIBDIR for install libraries, it will auto be: lib/multiarch-tuple for Debian.

But I understand the $LIB_SUFFIX here is defined for help to install extension libs to same install direction of Weston, in this case our expectation is installing to: lib/x86_64-linux-gnu.

If we applied this, extension's libs will install in the 'lib' of CMAKE_INSTALL_PREFIX, when we run the weston, it should show the issue like:
cant_load_module
We can avoid this issue via using the WESTON_MODULE_MAP variable when run Weston: https://github.com/khangtb1/wayland-ivi-extension/blob/weston_main_compatible/README#L49. But I think the better solution here is: set the -DLIB_SUFFIX=//multiarch-tuple when building for Debian

**Comment by khangtb1** [comment]
Hi @HarshaMM  @efriedrich 

This is a link for more information for WESTON_MODULE_MAP: https://gitlab.freedesktop.org/wayland/weston/-/commit/e03c111e4

As I see, there is no way to config this variable via .ini file, it must be from the user definition. We can load our modules on anywhere via defining the path of module in WESTON_MODULE_MAP.

In the latest weston branch (https://gitlab.freedesktop.org/wayland/weston/-/commit/eaf2de34411a281e72cc2334a40511cbce3ed4fd), the wet_load_module_entrypoint is removed, we must to use the weston_load_module to load the input-controller and id-agent-module in the ivi-controller. So with this change, we must use the WESTON_MODULE_MAP to define the path of modules, because ivi-controller can't access some internal paths, they are generated when weston building.

**Comment by rajendraprasadkj** [comment]
>

**Comment by rajendraprasadkj** [comment]
Sorry, closed by accident, reopened the PR again.

**Comment by rajendraprasadkj** [comment]
> Hi @rajendraprasadkj
> 
> As I understand this PR here: when using the CMAKE_INSTALL_LIBDIR for install libraries, it will auto be: lib/multiarch-tuple for Debian.
> 
> But I understand the $LIB_SUFFIX here is defined for help to install extension libs to same installed direction of Weston, in this case our expectation is installing to: lib/x86_64-linux-gnu.

As I understood LIB_SUFIX was introduced (https://github.com/COVESA/wayland-ivi-extension/commit/f887969606d881d9aea02893b68d4ec35ece8d78) to install libraries to lib or lib64 directories according to the CPU architecture.

> If we applied this, extension's libs will install in the 'lib' of CMAKE_INSTALL_PREFIX, when we run the weston, it should show the issue like: cant_load_module We can avoid this issue via using the WESTON_MODULE_MAP variable when run Weston: https://github.com/khangtb1/wayland-ivi-extension/blob/weston_main_compatible/README#L49. But I think the better solution here is: set the -DLIB_SUFFIX=//multiarch-tuple when building for Debian

Could see that by default meson's libdir is `lib/x86_64-linux-gnu`

`  --libdir LIBDIR       Library directory (default: lib/x86_64-linux-gnu).`

and cmake uses the following if the GNUInstallDirs are included:
` 
LIBDIR
    object code libraries (lib or lib64 or lib/<multiarch-tuple> on Debian)
`

In a docker environment, using cmake (v  _3.13.4_), the libs are getting installed in `<CMAKE_INSTALL_PREFIX>/lib` directory.

Will check further and update.

**Comment by rajendraprasadkj** [comment]
Could observe the following from the Cmake code (https://github.com/Kitware/CMake/blob/30c3effa89ceda247cd2ff29b5d3f4da8c7a8ff6/Modules/GNUInstallDirs.cmake#L223)

```
  if(CMAKE_SYSTEM_NAME MATCHES "^(Linux|kFreeBSD|GNU)$"
      AND NOT CMAKE_CROSSCOMPILING)
    if (EXISTS "/etc/debian_version") # is this a debian system ?
      if(CMAKE_LIBRARY_ARCHITECTURE)
        if("${CMAKE_INSTALL_PREFIX}" MATCHES "^/usr/?$")
          set(_LIBDIR_DEFAULT "lib/${CMAKE_LIBRARY_ARCHITECTURE}")
        endif()
```

The above additional condition which is checked even-if the build system is debian. This is mentioned in the later version of Cmake documentation. https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

```
LIBDIR

    object code libraries (lib or lib64)

    On Debian, this may be lib/<multiarch-tuple> when CMAKE_INSTALL_PREFIX is /usr.
```

Could observe that the libraries are installed to lib/x86_64-linux-gnu when CMAKE_INSTALL_PREFIX  is /usr.

So while building, if the CMAKE_INSTALL_PREFIX  is not /usr, we need set the  CMAKE_INSTALL_LIBDIR explicitly.

**Comment by rajendraprasadkj** [comment]
> @rajendraprasadkj ,
> 
> I also see necessity include the module https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html. I do not have an extensive knowledge of cmake. It would be great if you can check need for inclusion of gnuinstalldir

`GNUInstallDirs` defines the standard installation directories (https://cmake.org/cmake/help/v3.13/module/GNUInstallDirs.html).
If the above is not included the build will fail with the following error:
```
CMake Error at ivi-layermanagement-api/ilmInput/CMakeLists.txt:84 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "ilmInput".

```

**Comment by khangtb1** [comment]
> x86_64-linux-gnu

Thank @rajendraprasadkj to investigating the issue.
I tested with the  build steps:
    1. cd wayland-ivi-extension, mkdir build and cd build
    2. cmake -DBUILD_ILM_API_TESTS=ON  -DCMAKE_INSTALL_PREFIX=$WLD -DCMAKE_INSTALL_LIBDIR=$WLD/lib/x86_64-linux-gnu ../
    3. make install

I can see the libs of extension are installing to our expected folder. 
Tested-by: Tran Ba Khang [Khang.TranBa@vn.bosch.com](mailto:Khang.TranBa@vn.bosch.com)

**Review by khangtb1 — APPROVED** [review]

**Comment by efriedrich** [comment]
> > x86_64-linux-gnu
> 
> Thank @rajendraprasadkj to investigating the issue. I tested with the build steps: 1. cd wayland-ivi-extension, mkdir build and cd build 2. cmake -DBUILD_ILM_API_TESTS=ON -DCMAKE_INSTALL_PREFIX=$WLD -DCMAKE_INSTALL_LIBDIR=$WLD/lib/x86_64-linux-gnu ../ 3. make install
> 
> I can see the libs of extension are installing to our expected folder. Tested-by: Tran Ba Khang [Khang.TranBa@vn.bosch.com](mailto:Khang.TranBa@vn.bosch.com)

I would expect we don't need to add the "lib/x86_64-linux-gnu " explicitly and we would get it from the weston packaged config from the system. 
@khangtb1 could you check this and make if part of cmake file..

**Comment by khangtb1** [comment]
> > > x86_64-linux-gnu
> > 
> > 
> > Thank @rajendraprasadkj to investigating the issue. I tested with the build steps: 1. cd wayland-ivi-extension, mkdir build and cd build 2. cmake -DBUILD_ILM_API_TESTS=ON -DCMAKE_INSTALL_PREFIX=$WLD -DCMAKE_INSTALL_LIBDIR=$WLD/lib/x86_64-linux-gnu ../ 3. make install
> > I can see the libs of extension are installing to our expected folder. Tested-by: Tran Ba Khang [Khang.TranBa@vn.bosch.com](mailto:Khang.TranBa@vn.bosch.com)
> 
> I would expect we don't need to add the "lib/x86_64-linux-gnu " explicitly and we would get it from the weston packaged config from the system. @khangtb1 could you check this and make if part of cmake file..

Hello @efriedrich  and @rajendraprasadkj 

I looked to weston pkgconfig, then I see that: there is the LIBDIR variable, it defined the weston libraries directory. we can base on that to install ivi-modules to that. You can see on https://github.com/COVESA/wayland-ivi-extension/commit/650019ce8a352b5cc37c142f8eb116dd7912c005. 

The command should use: `cmake -DBUILD_ILM_API_TESTS=ON  -DCMAKE_INSTALL_PREFIX=$WLD ../ `
The output: 
- ilm libs install to: CMAKE_INSTALL_PREFIX\lib
- examples install to: CMAKE_INSTALL_PREFIX\bin
- ivi-modules install to: WESTON_LIBDIR\weston

**Comment by efriedrich** [comment]
> > > > x86_64-linux-gnu
> > > 
> > > 
> > > Thank @rajendraprasadkj to investigating the issue. I tested with the build steps: 1. cd wayland-ivi-extension, mkdir build and cd build 2. cmake -DBUILD_ILM_API_TESTS=ON -DCMAKE_INSTALL_PREFIX=$WLD -DCMAKE_INSTALL_LIBDIR=$WLD/lib/x86_64-linux-gnu ../ 3. make install
> > > I can see the libs of extension are installing to our expected folder. Tested-by: Tran Ba Khang [Khang.TranBa@vn.bosch.com](mailto:Khang.TranBa@vn.bosch.com)
> > 
> > 
> > I would expect we don't need to add the "lib/x86_64-linux-gnu " explicitly and we would get it from the weston packaged config from the system. @khangtb1 could you check this and make if part of cmake file..
> 
> Hello @efriedrich and @rajendraprasadkj
> 
> I looked to weston pkgconfig, then I see the LIBDIR variable, it defined the weston libraries directory. we can base on that to install ivi-modules to that. You can see on [650019c](https://github.com/COVESA/wayland-ivi-extension/commit/650019ce8a352b5cc37c142f8eb116dd7912c005).
> 
> The command should use: `cmake -DBUILD_ILM_API_TESTS=ON -DCMAKE_INSTALL_PREFIX=$WLD ../ ` The output:
> 
> * ilm libs install to: CMAKE_INSTALL_PREFIX\lib
> * examples install to: CMAKE_INSTALL_PREFIX\bin
> * ivi-modules install to: WESTON_LIBDIR\weston

I agree to the changes! we can go ahead!

**Comment by rajendraprasadkj** [comment]
> > > > > x86_64-linux-gnu
> > > > 
> > > > 
> > > > Thank @rajendraprasadkj to investigating the issue. I tested with the build steps: 1. cd wayland-ivi-extension, mkdir build and cd build 2. cmake -DBUILD_ILM_API_TESTS=ON -DCMAKE_INSTALL_PREFIX=$WLD -DCMAKE_INSTALL_LIBDIR=$WLD/lib/x86_64-linux-gnu ../ 3. make install
> > > > I can see the libs of extension are installing to our expected folder. Tested-by: Tran Ba Khang [Khang.TranBa@vn.bosch.com](mailto:Khang.TranBa@vn.bosch.com)
> > > 
> > > 
> > > I would expect we don't need to add the "lib/x86_64-linux-gnu " explicitly and we would get it from the weston packaged config from the system. @khangtb1 could you check this and make if part of cmake file..
> > 
> > 
> > Hello @efriedrich and @rajendraprasadkj
> > I looked to weston pkgconfig, then I see the LIBDIR variable, it defined the weston libraries directory. we can base on that to install ivi-modules to that. You can see on [650019c](https://github.com/COVESA/wayland-ivi-extension/commit/650019ce8a352b5cc37c142f8eb116dd7912c005).
> > The command should use: `cmake -DBUILD_ILM_API_TESTS=ON -DCMAKE_INSTALL_PREFIX=$WLD ../ ` The output:
> > 
> > * ilm libs install to: CMAKE_INSTALL_PREFIX\lib

one problem is that, for Debian systems, we would need the ilm libraries to be installed in  `lib/<multiarch-tuple>` when CMAKE_INSTALL_PREFIX is `/usr`.

We could install it to `${CMAKE_INSTALL_LIBDIR}`  which will install it to `lib or lib64 `when CMAKE_INSTALL_PREFIX is not `/usr` and `lib/<multiarch-tuple>` when CMAKE_INSTALL_PREFIX is `/usr`

> > * examples install to: CMAKE_INSTALL_PREFIX\bin
> > * ivi-modules install to: WESTON_LIBDIR\weston
> 
> I agree to the changes! we can go ahead!

I agree, can also see a WESTON_PKGLIBEXECDIR in weston.pc. Can we use it.

```prefix=/usr
libdir=${prefix}/lib/aarch64-linux-gnu
includedir=${prefix}/include

libexecdir=${prefix}/lib/aarch64-linux-gnu
pkglibexecdir=${libexecdir}/weston
```

**Comment by khangtb1** [comment]
> > > > > > x86_64-linux-gnu
> > > > > 
> > > > > 
> > > > > Thank @rajendraprasadkj to investigating the issue. I tested with the build steps: 1. cd wayland-ivi-extension, mkdir build and cd build 2. cmake -DBUILD_ILM_API_TESTS=ON -DCMAKE_INSTALL_PREFIX=$WLD -DCMAKE_INSTALL_LIBDIR=$WLD/lib/x86_64-linux-gnu ../ 3. make install
> > > > > I can see the libs of extension are installing to our expected folder. Tested-by: Tran Ba Khang [Khang.TranBa@vn.bosch.com](mailto:Khang.TranBa@vn.bosch.com)
> > > > 
> > > > 
> > > > I would expect we don't need to add the "lib/x86_64-linux-gnu " explicitly and we would get it from the weston packaged config from the system. @khangtb1 could you check this and make if part of cmake file..
> > > 
> > > 
> > > Hello @efriedrich and @rajendraprasadkj
> > > I looked to weston pkgconfig, then I see the LIBDIR variable, it defined the weston libraries directory. we can base on that to install ivi-modules to that. You can see on [650019c](https://github.com/COVESA/wayland-ivi-extension/commit/650019ce8a352b5cc37c142f8eb116dd7912c005).
> > > The command should use: `cmake -DBUILD_ILM_API_TESTS=ON -DCMAKE_INSTALL_PREFIX=$WLD ../ ` The output:
> > > 
> > > * ilm libs install to: CMAKE_INSTALL_PREFIX\lib
> 
> one problem is that, for Debian systems, we would need the ilm libraries to be installed in `lib/<multiarch-tuple>` when CMAKE_INSTALL_PREFIX is `/usr`.
> 
> We could install it to `${CMAKE_INSTALL_LIBDIR}` which will install it to `lib or lib64 `when CMAKE_INSTALL_PREFIX is not `/usr` and `lib/<multiarch-tuple>` when CMAKE_INSTALL_PREFIX is `/usr`
> 
> > > * examples install to: CMAKE_INSTALL_PREFIX\bin
> > > * ivi-modules install to: WESTON_LIBDIR\weston
> > 
> > 
> > I agree to the changes! we can go ahead!
> 
> I agree, can also see a WESTON_PKGLIBEXECDIR in weston.pc. Can we use it.
> 
> ```
> libdir=${prefix}/lib/aarch64-linux-gnu
> includedir=${prefix}/include
> 
> libexecdir=${prefix}/lib/aarch64-linux-gnu
> pkglibexecdir=${libexecdir}/weston
> ```

Hi @rajendraprasadkj , thanks for your responding. 

As I see on my side, I see the different of pkglibexecdir with your side. what was your build command?
`prefix=/home/kra1hc/install
libdir=${prefix}/lib/x86_64-linux-gnu
includedir=${prefix}/include

libexecdir=${prefix}/libexec
pkglibexecdir=${libexecdir}/weston`

**Comment by rajendraprasadkj** [comment]
> > > > > > > x86_64-linux-gnu
> > > > > > 
> > > > > > 
> > > > > > Thank @rajendraprasadkj to investigating the issue. I tested with the build steps: 1. cd wayland-ivi-extension, mkdir build and cd build 2. cmake -DBUILD_ILM_API_TESTS=ON -DCMAKE_INSTALL_PREFIX=$WLD -DCMAKE_INSTALL_LIBDIR=$WLD/lib/x86_64-linux-gnu ../ 3. make install
> > > > > > I can see the libs of extension are installing to our expected folder. Tested-by: Tran Ba Khang [Khang.TranBa@vn.bosch.com](mailto:Khang.TranBa@vn.bosch.com)
> > > > > 
> > > > > 
> > > > > I would expect we don't need to add the "lib/x86_64-linux-gnu " explicitly and we would get it from the weston packaged config from the system. @khangtb1 could you check this and make if part of cmake file..
> > > > 
> > > > 
> > > > Hello @efriedrich and @rajendraprasadkj
> > > > I looked to weston pkgconfig, then I see the LIBDIR variable, it defined the weston libraries directory. we can base on that to install ivi-modules to that. You can see on [650019c](https://github.com/COVESA/wayland-ivi-extension/commit/650019ce8a352b5cc37c142f8eb116dd7912c005).
> > > > The command should use: `cmake -DBUILD_ILM_API_TESTS=ON -DCMAKE_INSTALL_PREFIX=$WLD ../ ` The output:
> > > > 
> > > > * ilm libs install to: CMAKE_INSTALL_PREFIX\lib
> > 
> > 
> > one problem is that, for Debian systems, we would need the ilm libraries to be installed in `lib/<multiarch-tuple>` when CMAKE_INSTALL_PREFIX is `/usr`.
> > We could install it to `${CMAKE_INSTALL_LIBDIR}` which will install it to `lib or lib64 `when CMAKE_INSTALL_PREFIX is not `/usr` and `lib/<multiarch-tuple>` when CMAKE_INSTALL_PREFIX is `/usr`
> > > > * examples install to: CMAKE_INSTALL_PREFIX\bin
> > > > * ivi-modules install to: WESTON_LIBDIR\weston
> > > 
> > > 
> > > I agree to the changes! we can go ahead!
> > 
> > 
> > I agree, can also see a WESTON_PKGLIBEXECDIR in weston.pc. Can we use it.
> > ```
> > libdir=${prefix}/lib/aarch64-linux-gnu
> > includedir=${prefix}/include
> > 
> > libexecdir=${prefix}/lib/aarch64-linux-gnu
> > pkglibexecdir=${libexecdir}/weston
> > ```
> 
> Hi @rajendraprasadkj , thanks for your responding.
> 
> As I see on my side, I see the different of pkglibexecdir with your side. what was your build command? `prefix=/home/kra1hc/install libdir=${prefix}/lib/x86_64-linux-gnu includedir=${prefix}/include
> 
> libexecdir=${prefix}/libexec pkglibexecdir=${libexecdir}/weston`

I took `weston.pc` from Apertis build. Understood, then we better take `WESTON_LIBDIR\weston` as you proposed.

**Comment by khangtb1** [comment]
> > > > > > > > x86_64-linux-gnu
> > > > > > > 
> > > > > > > 
> > > > > > > Thank @rajendraprasadkj to investigating the issue. I tested with the build steps: 1. cd wayland-ivi-extension, mkdir build and cd build 2. cmake -DBUILD_ILM_API_TESTS=ON -DCMAKE_INSTALL_PREFIX=$WLD -DCMAKE_INSTALL_LIBDIR=$WLD/lib/x86_64-linux-gnu ../ 3. make install
> > > > > > > I can see the libs of extension are installing to our expected folder. Tested-by: Tran Ba Khang [Khang.TranBa@vn.bosch.com](mailto:Khang.TranBa@vn.bosch.com)
> > > > > > 
> > > > > > 
> > > > > > I would expect we don't need to add the "lib/x86_64-linux-gnu " explicitly and we would get it from the weston packaged config from the system. @khangtb1 could you check this and make if part of cmake file..
> > > > > 
> > > > > 
> > > > > Hello @efriedrich and @rajendraprasadkj
> > > > > I looked to weston pkgconfig, then I see the LIBDIR variable, it defined the weston libraries directory. we can base on that to install ivi-modules to that. You can see on [650019c](https://github.com/COVESA/wayland-ivi-extension/commit/650019ce8a352b5cc37c142f8eb116dd7912c005).
> > > > > The command should use: `cmake -DBUILD_ILM_API_TESTS=ON -DCMAKE_INSTALL_PREFIX=$WLD ../ ` The output:
> > > > > 
> > > > > * ilm libs install to: CMAKE_INSTALL_PREFIX\lib
> > > 
> > > 
> > > one problem is that, for Debian systems, we would need the ilm libraries to be installed in `lib/<multiarch-tuple>` when CMAKE_INSTALL_PREFIX is `/usr`.
> > > We could install it to `${CMAKE_INSTALL_LIBDIR}` which will install it to `lib or lib64 `when CMAKE_INSTALL_PREFIX is not `/usr` and `lib/<multiarch-tuple>` when CMAKE_INSTALL_PREFIX is `/usr`
> > > > > * examples install to: CMAKE_INSTALL_PREFIX\bin
> > > > > * ivi-modules install to: WESTON_LIBDIR\weston
> > > > 
> > > > 
> > > > I agree to the changes! we can go ahead!
> > > 
> > > 
> > > I agree, can also see a WESTON_PKGLIBEXECDIR in weston.pc. Can we use it.
> > > ```
> > > libdir=${prefix}/lib/aarch64-linux-gnu
> > > includedir=${prefix}/include
> > > 
> > > libexecdir=${prefix}/lib/aarch64-linux-gnu
> > > pkglibexecdir=${libexecdir}/weston
> > > ```
> > 
> > 
> > Hi @rajendraprasadkj , thanks for your responding.
> > As I see on my side, I see the different of pkglibexecdir with your side. what was your build command? `prefix=/home/kra1hc/install libdir=${prefix}/lib/x86_64-linux-gnu includedir=${prefix}/include
> > libexecdir=${prefix}/libexec pkglibexecdir=${libexecdir}/weston`
> 
> I took `weston.pc` from Apertis build. Understood, then we better take `WESTON_LIBDIR\weston` as you proposed.

Thank @rajendraprasadkj, 
Due to I don't have permission to push code on this branch. I will create another PR base on this. thanks

**Comment by rajendraprasadkj** [comment]
Closing the PR as https://github.com/COVESA/wayland-ivi-extension/pull/153 is created with above code modifications

**Pull request closed without merging**
