### PR TITLE
Pull request for weston 10 and gcc 11 environment (Yocto kirkstone).

### PR DESCRIPTION
**Pull request by AGLExport**
This request aim to use wayland-ivi-extation in Yocto kirkstone.
This request is including un-merged previous work, it's contributed by Rajendraprasad K J .  Those patch port from meta-arago project.

I improved by more 3 patches.

### CODE REVIEW

**Comment by einarjon** [comment]
Nice job. You could squash commits  [46ef714](https://github.com/COVESA/wayland-ivi-extension/pull/130/commits/46ef7140611d684d1dbecd866608333e67a1985e), [8e12ca3](https://github.com/COVESA/wayland-ivi-extension/pull/130/commits/8e12ca39c09e8bfcae4da83fbe92d4dc16ae19c1) and [f4fc9aa](https://github.com/COVESA/wayland-ivi-extension/pull/130/commits/f4fc9aa3e575ac02241fc8e7b33618040ce411b9)
to a single one for a cleaner PR

**Comment by AGLExport** [comment]
I create  #131.

**Comment by khangtb1** [comment]
This Pr should close, the #131 contains those changes
Review-by: Tran Ba Khang<Khang.TranBa@vn.bosch.com>

**Comment by einarjon** [comment]
Don't create new PRs with the same thing, just modify the one you have.

**Pull request closed without merging**
