### PR TITLE
Weston 10 compatible

### PR DESCRIPTION
**Pull request by khangtb1**
CMakeLists: update libweston to version 10
    Update the libweston-10 on ivi-id-agent cmake file.
    Update the libweston-10-protocols on simple-weston-client cmake file

### CODE REVIEW

**Comment by khangtb1** [comment]
This is the new sequence for handle the default seat in wayland-ivi-extension:

default_seat_improvement

**Comment by khangtb1** [comment]
This Pr is depended on #148

**Review by HarshaMM — APPROVED** [review]
Reviewed-by: Harsha M M <harsha.manjulamallikarjun@in.bosch.com>

**Comment by khangtb1** [comment]
This is depended on https://github.com/COVESA/wayland-ivi-extension/pull/157

**Review by efriedrich — APPROVED** [review]
Reviewed-by: Eugen Friedrich <efriedrich@de.adit-jv.com>

**Pull request merged**
